/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core;

import aesd.ds.implementations.nonlinear.symtable.Trie;
import com.formdev.flatlaf.FlatLightLaf;

import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author bv110309
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName());

    private Trie<List<Position>> trie;

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        
        initComponents();
        
        listResultado.setModel( new DefaultListModel<String>() );
        
        textPaneTexto.setText("by sea sells she shells shore the by by shore she she sea ball pen chair");

        trie = new Trie<>();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneTexto = new javax.swing.JScrollPane();
        textPaneTexto = new javax.swing.JTextPane();
        painelPesquisa = new javax.swing.JPanel();
        lblBuscarPor = new javax.swing.JLabel();
        txtBuscarPor = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        scrollPaneResultado = new javax.swing.JScrollPane();
        listResultado = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busca em Trie");

        scrollPaneTexto.setViewportView(textPaneTexto);

        painelPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar"));

        lblBuscarPor.setText("Buscar por:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        listResultado.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPaneResultado.setViewportView(listResultado);

        javax.swing.GroupLayout painelPesquisaLayout = new javax.swing.GroupLayout(painelPesquisa);
        painelPesquisa.setLayout(painelPesquisaLayout);
        painelPesquisaLayout.setHorizontalGroup(
            painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneResultado)
                    .addGroup(painelPesquisaLayout.createSequentialGroup()
                        .addComponent(lblBuscarPor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarPor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPesquisaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        painelPesquisaLayout.setVerticalGroup(
            painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarPor)
                    .addComponent(txtBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPaneTexto))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String[] searchValues = txtBuscarPor.getText().split( "[,\s]" );

        System.out.println( searchValues.length );

        if ( txtBuscarPor.getText().trim().isEmpty() ) {
            setListText( "Enter a word to search" );
        } else if (searchValues.length > 1 ) {
            setListText( "It is not possible to find more than one word");
        } else {
            String searchValue = searchValues[0];

            trie.clear();
            buildTrie();

            if ( trie.contains(searchValue) ) {

                clearList();
                updateList(searchValue);

                modifyOccurrencesInTextPane( searchValue, Color.BLUE );
            } else {
                setListText( "No results found" );
            }

        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void updateList(String searchValue) {

        // retrieves the list template and clears it
        DefaultListModel<String> model = (DefaultListModel<String>) listResultado.getModel();

        // add the occurrences of the words
        for (Position p : trie.get(searchValue)) {
            String itemList = String.format(
                    "%s: (row %d, column %d;)",
                    searchValue,
                    p.getRow(),
                    p.getColumn()
            );
            model.addElement(itemList);
        }

    }

    private void setListText( String text ) {
        DefaultListModel<String> model = (DefaultListModel<String>) listResultado.getModel();
        model.clear();
        model.addElement( text );
    }

    private void clearList(){
        // retrieves the list template and clears it
        DefaultListModel<String> model = (DefaultListModel<String>) listResultado.getModel();
        model.clear();
    }

    private void buildTrie() {

        // variables for creating occurrences positions
        int row = 1;
        int col = 1;
        int currentWidth = 0;

        // get the metrics for the current source
        FontMetrics fm = textPaneTexto.getFontMetrics(textPaneTexto.getFont());

        // calculate the visible width of the JPaneText
        int width = textPaneTexto.getWidth() - textPaneTexto.getInsets().left - textPaneTexto.getInsets().right;

        // builds the trie
        for ( String s : textPaneTexto.getText().split( " " ) ) {

            // add up the width of the characters in the current word
            for ( char c : s.toCharArray() ) {
                int charWidth = fm.charWidth(c);
                currentWidth += charWidth;
            }

            // add the width of the space between that word and the next one
            int spaceWidth = fm.charWidth(' ');
            currentWidth += spaceWidth;

            // check whether the current width is greater than the width of the JPaneText
            if ( currentWidth > width ) {
                row++;
                currentWidth = 0;
                col = 1;
            }

            // insertion into the trie
            if ( trie.contains(s) ) {
                trie.get(s).add( new Position( row, col ) );
            } else {
                List<Position> newList = new ArrayList<>();
                newList.add(new Position( row, col ) );
                trie.put( s, newList );
            }

            // sum the number of characters to update the current column
            col += s.length() + 1;

        }
    }

    private void modifyOccurrencesInTextPane(String searchValue, Color color ) {
        
        try {
            
            SimpleAttributeSet as = new SimpleAttributeSet();

            String[] words = textPaneTexto.getText().split( " " );

            textPaneTexto.setText( "" );

            for ( String word : words ) {

                if ( word.equals( searchValue ) ) {
                    StyleConstants.setBold( as, true );
                    StyleConstants.setItalic( as, true );
                    StyleConstants.setForeground( as, color );
                } else {
                    StyleConstants.setBold( as, false );
                    StyleConstants.setItalic( as, false );
                    StyleConstants.setForeground( as, Color.BLACK );
                }

                String insert = word + " ";
                textPaneTexto.getDocument().insertString( textPaneTexto.getDocument().getLength(), insert, as );
            }
            
        } catch ( BadLocationException exc ) {
            exc.printStackTrace();
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(() -> new JanelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel lblBuscarPor;
    private javax.swing.JList<String> listResultado;
    private javax.swing.JPanel painelPesquisa;
    private javax.swing.JScrollPane scrollPaneResultado;
    private javax.swing.JScrollPane scrollPaneTexto;
    private javax.swing.JTextPane textPaneTexto;
    private javax.swing.JTextField txtBuscarPor;
    // End of variables declaration//GEN-END:variables
}
